title: Manuel Duarte
logo: /assets/img/headshot_circle.png
description: AI Training Specialist & Bilingual Linguist/Software Development Engineering Student
#show_downloads: false
theme: jekyll-theme-minimal
